// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: skillchain/marketplace/genesis.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { JobPosting } from "./job_posting";
import { Milestone } from "./milestone";
import { Params } from "./params";
import { Project } from "./project";
import { Proposal } from "./proposal";

export const protobufPackage = "skillchain.marketplace";

/** GenesisState defines the marketplace module's genesis state. */
export interface GenesisState {
  /** params defines all the parameters of the module. */
  params: Params | undefined;
  jobPostingList: JobPosting[];
  proposalList: Proposal[];
  projectList: Project[];
  milestoneList: Milestone[];
}

function createBaseGenesisState(): GenesisState {
  return { params: undefined, jobPostingList: [], proposalList: [], projectList: [], milestoneList: [] };
}

export const GenesisState: MessageFns<GenesisState> = {
  encode(message: GenesisState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    for (const v of message.jobPostingList) {
      JobPosting.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.proposalList) {
      Proposal.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.projectList) {
      Project.encode(v!, writer.uint32(34).fork()).join();
    }
    for (const v of message.milestoneList) {
      Milestone.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenesisState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenesisState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.jobPostingList.push(JobPosting.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.proposalList.push(Proposal.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.projectList.push(Project.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.milestoneList.push(Milestone.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenesisState {
    return {
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
      jobPostingList: globalThis.Array.isArray(object?.jobPostingList)
        ? object.jobPostingList.map((e: any) => JobPosting.fromJSON(e))
        : [],
      proposalList: globalThis.Array.isArray(object?.proposalList)
        ? object.proposalList.map((e: any) => Proposal.fromJSON(e))
        : [],
      projectList: globalThis.Array.isArray(object?.projectList)
        ? object.projectList.map((e: any) => Project.fromJSON(e))
        : [],
      milestoneList: globalThis.Array.isArray(object?.milestoneList)
        ? object.milestoneList.map((e: any) => Milestone.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GenesisState): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    if (message.jobPostingList?.length) {
      obj.jobPostingList = message.jobPostingList.map((e) => JobPosting.toJSON(e));
    }
    if (message.proposalList?.length) {
      obj.proposalList = message.proposalList.map((e) => Proposal.toJSON(e));
    }
    if (message.projectList?.length) {
      obj.projectList = message.projectList.map((e) => Project.toJSON(e));
    }
    if (message.milestoneList?.length) {
      obj.milestoneList = message.milestoneList.map((e) => Milestone.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenesisState>, I>>(base?: I): GenesisState {
    return GenesisState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenesisState>, I>>(object: I): GenesisState {
    const message = createBaseGenesisState();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    message.jobPostingList = object.jobPostingList?.map((e) => JobPosting.fromPartial(e)) || [];
    message.proposalList = object.proposalList?.map((e) => Proposal.fromPartial(e)) || [];
    message.projectList = object.projectList?.map((e) => Project.fromPartial(e)) || [];
    message.milestoneList = object.milestoneList?.map((e) => Milestone.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
