// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: skillchain/analytics/genesis.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";
import { PlatformMetric } from "./platform_metric";
import { RevenueRecord } from "./revenue_record";
import { UserActivity } from "./user_activity";

export const protobufPackage = "skillchain.analytics";

/** GenesisState defines the analytics module's genesis state. */
export interface GenesisState {
  /** params defines all the parameters of the module. */
  params: Params | undefined;
  platformMetricList: PlatformMetric[];
  userActivityList: UserActivity[];
  revenueRecordList: RevenueRecord[];
}

function createBaseGenesisState(): GenesisState {
  return { params: undefined, platformMetricList: [], userActivityList: [], revenueRecordList: [] };
}

export const GenesisState: MessageFns<GenesisState> = {
  encode(message: GenesisState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    for (const v of message.platformMetricList) {
      PlatformMetric.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.userActivityList) {
      UserActivity.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.revenueRecordList) {
      RevenueRecord.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenesisState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenesisState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.platformMetricList.push(PlatformMetric.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userActivityList.push(UserActivity.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.revenueRecordList.push(RevenueRecord.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenesisState {
    return {
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
      platformMetricList: globalThis.Array.isArray(object?.platformMetricList)
        ? object.platformMetricList.map((e: any) => PlatformMetric.fromJSON(e))
        : [],
      userActivityList: globalThis.Array.isArray(object?.userActivityList)
        ? object.userActivityList.map((e: any) => UserActivity.fromJSON(e))
        : [],
      revenueRecordList: globalThis.Array.isArray(object?.revenueRecordList)
        ? object.revenueRecordList.map((e: any) => RevenueRecord.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GenesisState): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    if (message.platformMetricList?.length) {
      obj.platformMetricList = message.platformMetricList.map((e) => PlatformMetric.toJSON(e));
    }
    if (message.userActivityList?.length) {
      obj.userActivityList = message.userActivityList.map((e) => UserActivity.toJSON(e));
    }
    if (message.revenueRecordList?.length) {
      obj.revenueRecordList = message.revenueRecordList.map((e) => RevenueRecord.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenesisState>, I>>(base?: I): GenesisState {
    return GenesisState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenesisState>, I>>(object: I): GenesisState {
    const message = createBaseGenesisState();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    message.platformMetricList = object.platformMetricList?.map((e) => PlatformMetric.fromPartial(e)) || [];
    message.userActivityList = object.userActivityList?.map((e) => UserActivity.fromPartial(e)) || [];
    message.revenueRecordList = object.revenueRecordList?.map((e) => RevenueRecord.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
